// File generated by FlutterFire CLI.
// DO NOT EDIT.
//
// If you need to regenerate this file, run:
//   flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      // iOS is not configured
      // case TargetPlatform.iOS:
      //   return ios;

      // macOS is not configured
      // case TargetPlatform.macOS:
      //   return macos;

      // Windows is not configured
      // case TargetPlatform.windows:
      //   return windows;

      // Linux is not configured
      // case TargetPlatform.linux:
      //   return linux;

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-XinOq2dD0nVZ68N2xXsQSVnpquC_S1w',
    authDomain: 'baserentapp-0.firebaseapp.com',
    projectId: 'baserentapp-0',
    storageBucket: 'baserentapp-0.firebasestorage.app',
    messagingSenderId: '122374147282',
    appId: '1:122374147282:web:2e384fd81ec87ad70b710b',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWQX_UFzbYZONpv9ogxvr04tUk5bTDWu0',
    appId: '1:122374147282:android:dbc85ffcbca2f0a30b710b',
    messagingSenderId: '122374147282',
    projectId: 'baserentapp-0',
    storageBucket: 'baserentapp-0.firebasestorage.app',
  );
}
