import 'dart:async';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter_stripe/flutter_stripe.dart';
import 'firebase_options.dart'; // Generated by flutterfire configure

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  runZonedGuarded(() async {
    await Firebase.initializeApp(
      options: DefaultFirebaseOptions.currentPlatform,
    );

    // Initialize Stripe
    Stripe.publishableKey = 'pk_test_XXXXXXXXXXXXXXXXXXXXXXXX'; // Replace with your key
    await Stripe.instance.applySettings();

    runApp(const MyApp());
  }, (error, stack) {
    print('⚠️ Uncaught error: $error');
    print(stack);
  });

  FlutterError.onError = (details) {
    FlutterError.presentError(details);
    print('⚠️ FlutterError: ${details.exception}');
    print(details.stack);
  };
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Rental App',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(primarySwatch: Colors.blue),
      home: const HomePage(),
    );
  }
}

class HomePage extends StatefulWidget {
  const HomePage({super.key});

  @override
  State<HomePage> createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  final FirebaseAuth _auth = FirebaseAuth.instance;
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  User? user;
  String status = 'Initializing...';

  @override
  void initState() {
    super.initState();
    _signInAnonymously();
  }

  Future<void> _signInAnonymously() async {
    try {
      UserCredential cred = await _auth.signInAnonymously();
      setState(() {
        user = cred.user;
        status = 'Signed in as ${user?.uid}';
      });
    } catch (e, st) {
      print('⚠️ Auth error: $e');
      print(st);
      setState(() => status = 'Sign-in failed');
    }
  }

  Future<void> _addTestData() async {
    if (user == null) return;
    try {
      await _firestore.collection('test').add({'uid': user!.uid, 'timestamp': DateTime.now()});
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Data added to Firestore')),
      );
    } catch (e, st) {
      print('⚠️ Firestore error: $e');
      print(st);
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Failed to add data')),
      );
    }
  }

  Future<void> _testStripe() async {
    try {
      final paymentMethod = await Stripe.instance.createPaymentMethod(
        const PaymentMethodParams.card(paymentMethodData: PaymentMethodData()),
      );
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Payment Method created: ${paymentMethod.id}')),
      );
    } catch (e, st) {
      print('⚠️ Stripe error: $e');
      print(st);
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Payment failed')),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text('Rental App')),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Text(status),
            const SizedBox(height: 20),
            ElevatedButton(
              onPressed: _addTestData,
              child: const Text('Add Test Firestore Data'),
            ),
            const SizedBox(height: 20),
            ElevatedButton(
              onPressed: _testStripe,
              child: const Text('Test Stripe Payment'),
            ),
          ],
        ),
      ),
    );
  }
}